/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/zjINF96Kw0b
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { JSX, SVGProps } from "react"

export function HomePage() {
  return (
    <div key="1" className="w-full relative bg-[#1A202C] text-white">
      <section
        className="w-full py-12 md:py-24 lg:py-32"
      >
        <div
          className="container flex flex-col gap-4 px-4 text-center md:px-6"
        >
          <div
            className="space-y-2 mx-auto max-w-[600px]"
            style={{
              transform: "translateZ(50px)",
            }}
          >
            <div className="inline-block rounded-lg bg-[#805AD5] px-3 py-1 text-sm dark:bg-[#D1D5DB] ">
              About Me
            </div>
            <h2>Gamer. Developer</h2>
            <p className="text-[#805AD5] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-[#7F9CF5]">
              I turn ideas into beautiful and functional websites. I love creating web experiences that are both
              visually stunning and user-friendly.
            </p>
          </div>
          <div
            className="mx-auto flex flex-col items-center justify-center gap-4 min-[600px]:flex-row"
            style={{
              transform: "translateZ(100px)",
            }}
          >
            <div className="grid gap-2">
              <h3 className="text-lg font-semibold">Connect with Me</h3>
              <div className="flex items-center gap-2">
                <TwitterIcon className="w-4 h-4" />
                <span className="text-sm text-[#805AD5] dark:text-[#7F9CF5] dark:text-black">Twitter</span>
              </div>
              <div className="flex items-center gap-2">
                <GithubIcon className="w-4 h-4" />
                <span className="text-sm text-[#805AD5] dark:text-[#7F9CF5] dark:text-black">GitHub</span>
              </div>
              <div className="flex items-center gap-2">
                <DribbbleIcon className="w-4 h-4" />
                <span className="text-sm text-[#805AD5] dark:text-[#7F9CF5] dark:text-black">Dribbble</span>
              </div>
            </div>
            <div
              className="rounded-full overflow-hidden border-4 border-[#805AD5] dark:border-[#D1D5DB]"
              style={{
                transform: "translateZ(150px)",
              }}
            >
              <img
                alt="Profile Picture"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
            </div>
          </div>
        </div>
      </section>
      <section
        className="w-full py-12 md:py-24 lg:py-32"
        style={{
          perspective: "1000px",
        }}
      >
        <div
          className="container grid items-center gap-4 px-4 text-center md:px-6"
          style={{
            transformStyle: "preserve-3d",
          }}
        >
          <div
            className="space-y-2"
            style={{
              transform: "translateZ(50px)",
            }}
          >
            <div className="inline-block rounded-lg bg-[#805AD5] px-3 py-1 text-sm dark:bg-[#D1D5DB] dark:text-black">
              Portfolio
            </div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">My Work</h2>
            <p className="mx-auto max-w-[600px] text-[#805AD5] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-[#7F9CF5] dark:text-black">
              Check out some of my recent projects. Each one is a testament to my passion for clean design and seamless
              functionality.
            </p>
          </div>
          <div
            className="mx-auto grid max-w-5xl items-start gap-8 min-[400px]:grid-cols-2 md:gap-12 lg:gap-16"
            style={{
              transform: "translateZ(100px)",
            }}
          >
            <div className="flex flex-col gap-2">
              <img
                alt="Project 1"
                className="aspect-video overflow-hidden rounded-lg object-cover object-center border border-gray-200 border-[#805AD5] dark:border-[#D1D5DB] dark:border-gray-800"
                height="350"
                src="/placeholder.svg" 
                width="600"
              />
              <div className="space-y-2">
                <h3 className="text-xl font-bold">Project One</h3>
                <p className="text-sm text-[#805AD5] dark:text-[#7F9CF5] dark:text-black">
                  This was a website redesign for a local bakery. I focused on making the site more visually appealing
                  while ensuring that customers could easily access information about the bakerys products and opening
                  hours.
                </p>
              </div>
            </div>
            <div className="flex flex-col gap-2">
              <img
                alt="Project 2"
                className="aspect-video overflow-hidden rounded-lg object-cover object-center border border-gray-200 border-[#805AD5] dark:border-[#D1D5DB] dark:border-gray-800"
                height="350"
                src="/placeholder.svg"
                width="600"
              />
              <div className="space-y-2">
                <h3 className="text-xl font-bold">Project Two</h3>
                <p className="text-sm text-[#805AD5] dark:text-[#7F9CF5] dark:text-black">
                  For this project, I created a web app that allowed users to track their daily water intake. The app
                  featured a simple and intuitive interface, and users could set daily water intake goals and receive
                  reminders to stay hydrated.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section
        className="w-full py-12 md:py-24 lg:py-32"
        style={{
          perspective: "1000px",
        }}
      >
        <div
          className="container flex flex-col gap-4 px-4 text-center md:px-6"
          style={{
            transformStyle: "preserve-3d",
          }}
        >
          <div
            className="space-y-2"
            style={{
              transform: "translateZ(50px)",
            }}
          >
            <div className="inline-block rounded-lg bg-[#805AD5] px-3 py-1 text-sm dark:bg-[#D1D5DB] dark:text-black">
              Skills
            </div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">My Skills</h2>
            <p className="mx-auto max-w-[600px] text-[#805AD5] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-[#7F9CF5] dark:text-black">
              Im proficient in a variety of programming languages and frameworks, and Im always learning new skills to
              stay ahead of the curve.
            </p>
          </div>
          <div
            className="mx-auto grid max-w-sm gap-2 items-start sm:max-w-4xl sm:grid-cols-2 md:gap-4 lg:max-w-5xl lg:grid-cols-3"
            style={{
              transform: "translateZ(100px)",
            }}
          >
            <div className="inline-flex items-center gap-2">
              <CheckCircleIcon className="w-4 h-4" />
              <span className="text-sm font-medium text-[#805AD5] dark:text-[#7F9CF5] dark:text-black">HTML5</span>
            </div>
            <div className="inline-flex items-center gap-2">
              <CheckCircleIcon className="w-4 h-4" />
              <span className="text-sm font-medium text-[#805AD5] dark:text-[#7F9CF5] dark:text-black">CSS3</span>
            </div>
            <div className="inline-flex items-center gap-2">
              <CheckCircleIcon className="w-4 h-4" />
              <span className="text-sm font-medium text-[#805AD5] dark:text-[#7F9CF5] dark:text-black">JavaScript</span>
            </div>
            <div className="inline-flex items-center gap-2">
              <CheckCircleIcon className="w-4 h-4" />
              <span className="text-sm font-medium text-[#805AD5] dark:text-[#7F9CF5] dark:text-black">React</span>
            </div>
            <div className="inline-flex items-center gap-2">
              <CheckCircleIcon className="w-4 h-4" />
              <span className="text-sm font-medium text-[#805AD5] dark:text-[#7F9CF5] dark:text-black">Next.js</span>
            </div>
            <div className="inline-flex items-center gap-2">
              <CheckCircleIcon className="w-4 h-4" />
              <span className="text-sm font-medium text-[#805AD5] dark:text-[#7F9CF5] dark:text-black">
                Tailwind CSS
              </span>
            </div>
          </div>
        </div>
      </section>
      <section
        className="w-full py-12 md:py-24 lg:py-32"
        style={{
          perspective: "1000px",
        }}
      >
        <div
          className="container flex flex-col gap-4 px-4 text-center md:px-6"
          style={{
            transformStyle: "preserve-3d",
          }}
        >
          <div
            className="space-y-2"
            style={{
              transform: "translateZ(50px)",
            }}
          >
            <div className="inline-block rounded-lg bg-[#805AD5] px-3 py-1 text-sm dark:bg-[#D1D5DB] dark:text-black">
              Contact
            </div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Get in Touch</h2>
            <p className="mx-auto max-w-[600px] text-[#805AD5] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-[#7F9CF5] dark:text-black">
              Have a project in mind? Want to collaborate? Drop me a message, and Ill get back to you as soon as
              possible.
            </p>
          </div>
          <div
            className="mx-auto max-w-[400px] space-y-4"
            style={{
              transform: "translateZ(100px)",
            }}
          >
            <div className="grid gap-2">
              <Label className="text-sm" htmlFor="name">
                Name
              </Label>
              <Input id="name" placeholder="Enter your name" />
            </div>
            <div className="grid gap-2">
              <Label className="text-sm" htmlFor="email">
                Email
              </Label>
              <Input id="email" placeholder="Enter your email" />
            </div>
            <div className="grid gap-2">
              <Label className="text-sm" htmlFor="message">
                Message
              </Label>
              <Textarea className="min-h-[100px] resize-y" id="message" placeholder="Enter your message" />
            </div>
            <Button className="w-full" size="lg">
              Submit
            </Button>
          </div>
        </div>
      </section>
    </div>
  )
}


function TwitterIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function GithubIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function DribbbleIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M19.13 5.09C15.22 9.14 10 10.44 2.25 10.94" />
      <path d="M21.75 12.84c-6.62-1.41-12.14 1-16.38 6.32" />
      <path d="M8.56 2.75c4.37 6 6 9.42 8 17.72" />
    </svg>
  )
}


function CheckCircleIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>
  )
}
